[package]
name = "gitox"
version = "0.1.0"
authors = ["Callum Ward <calward@cisco.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.33.3"
sha-1 = "0.9.1"
tempfile = "3"
walkdir = "2"
